{
 "title": "Logging Dashboard",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Service",
    "query": {}
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {}
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total Count of Logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({container=\"$container\", stream=~\"$stream\", pod=~\"$pod\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count of Warning Logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({container=\"$container\", stream=~\"$stream\", pod=~\"$pod\"} |~ \"level=warn\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count of Error Logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({container=\"$container\", stream=~\"$stream\", pod=~\"$pod\"} |~ \"level=error\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"$container\", pod=~\"$pod\", stream=~\"$stream\"}"
    }
   ]
  }
 ]
}