apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.lab.net`)
      kind: Rule
      services:
        - name: victoria-metrics-stack-lab-grafana
          port: 80
