---
- name: "{{ 'Start' if state == 'up' else 'Stop' }} VPN on Client"
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  vars:
    state: up
  tasks:
    - name: "{{ 'Start' if state == 'up' else 'Stop' }} VPN"
      ansible.builtin.service:
        name: wg-quick@wg0
        state: "{{ 'started' if state == 'up' else 'stopped' }}"
        enabled: yes
