targetRevision: main
namespace: argocd

apps:
  grafana:
    enabled: true
    metadata:
      name: grafana-lab
    spec:
      project: addons
      source:
        repoURL: https://github.com/xaistrying/mini-homelab.git
        path: kubernetes/addons/grafana
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

  loki:
    enabled: true
    metadata:
      name: loki-stack-lab
    spec:
      project: addons
      source:
        repoURL: https://github.com/xaistrying/mini-homelab.git
        path: kubernetes/addons/loki
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

  victoriaMetrics:
    enabled: true
    metadata:
      name: victoria-metrics-stack-lab
    spec:
      project: addons
      source:
        repoURL: https://github.com/xaistrying/mini-homelab.git
        path: kubernetes/addons/victoria-metrics
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true

  chaosMesh:
    enabled: true
    metadata:
      name: chaos-mesh-lab
    spec:
      project: addons
      source:
        repoURL: https://github.com/xaistrying/mini-homelab.git
        path: kubernetes/addons/chaos-mesh
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: chaos-mesh
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true

  k6:
    enabled: true
    metadata:
      name: k6-lab
    spec:
      project: addons
      source:
        repoURL: https://github.com/xaistrying/mini-homelab.git
        path: kubernetes/addons/k6
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: lab
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
