apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: chaos-mesh-dashboard
  namespace: chaos-mesh
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`chaos-mesh.lab.net`)
      kind: Rule
      services:
        - name: chaos-mesh-dashboard
          port: 2333
