victoria-metrics-k8s-stack:
  fullnameOverride: vm

  prometheus-node-exporter:
    enabled: true
    grafanaDashboard:
      enabled: false

  kube-state-metrics:
    enabled: true
    grafanaDashboard:
      enabled: false

  victoria-metrics-operator:
    enabled: true
    admissionWebhooks:
      enabled: false
    createCRD: true

  alertmanager:
    enabled: false

  vmalert:
    enabled: false

  grafana:
    enabled: true
    defaultDashboardsEnabled: false
    sidecar:
      datasources:
        enabled: true
        createVMReplicasDatasources: false
      dashboards:
        enabled: true

  defaultRules:
    create: false
